### ISSUE TITLE
switch dates to ISO 8601

### ISSUE THREAD

**Issue by andrewsu** [biothings/discovery-app#10]
When registering a dataset (I think in the DataDistribution section), I see this dialog box:

![image](https://user-images.githubusercontent.com/2635409/81134607-23b91b00-8f0a-11ea-8cf8-6ade11336ffb.png)

To promote good data practices, suggest switching to `YYYY-MM-DD` to follow [ISO 8601 standard](https://en.wikipedia.org/wiki/ISO_8601).

**Comment by marcodarko** [comment]
All dates are automatically reformatted to YYYY-MM-DD format regardless of the way a browser displays the date input.
