### ISSUE TITLE
Suggestion: Enable selection of `optional`, `recommended` and not just `required`

### ISSUE THREAD

**Issue by gtsueng** [biothings/discovery-app#106]
The DDE UI allows the user to select whether or not a property is `required`. Enable users to also select whether or not a property is `recommended` or `optional`.

**Comment by marcodarko** [comment]
Will be addressed in PR https://github.com/biothings/discovery-app/pull/111

**Comment by gtsueng** [comment]
The exported json looks the way it should. Just need DDE to realize that the json is valid!
