### ISSUE TITLE
dataset registration: confusing UX, and registration failure

### ISSUE THREAD

**Issue by andrewsu** [biothings/discovery-app#11]
After I enter all metadata using the [NIAID guide](https://discovery.biothings.io/guide/niaid), I get to this screen:

![image](https://user-images.githubusercontent.com/2635409/81134736-84485800-8f0a-11ea-9cc0-7e1cfc030e0c.png)

Clicking the "Register" link produces this modal:

![image](https://user-images.githubusercontent.com/2635409/81134760-99bd8200-8f0a-11ea-88c5-fb1910af0a52.png)

Clicking "Register Now" seems to just make the modal disappear -- was expecting it to report back "Success" or "Failure" on a new page. 

It appears that the dataset was _not_ successfully registered since I do not see it at https://discovery.biothings.io/dataset

**Comment by marcodarko** [comment]
This issue has been fixed, the response format from an error changed and the modal was updated to display info from the new format. Modal will list the property(ies) that are causing the issue, parent info if any, and full error message.
