### ISSUE TITLE
Feature request: preview the metadata before dataset registration

### ISSUE THREAD

**Issue by flaneuse** [biothings/discovery-app#117]
When you're registering a dataset, it'd be nice to be able to see a preview of the dataset page before you click register. I know you can "preview progress", but 1) that's hard to find, unless you know where to look; 2) it's hard to read .json.
<img width="1365" alt="Screen Shot 2022-02-09 at 4 28 44 PM" src="https://user-images.githubusercontent.com/8041065/153313735-9c13511d-c7da-498a-8c77-eefa4ac5038c.png">

Would be cool to have a button near "register" which would let you preview the dataset page:
<img width="1370" alt="Screen Shot 2022-02-09 at 4 29 51 PM" src="https://user-images.githubusercontent.com/8041065/153313803-a1592778-9ca1-4fd0-a4f1-52b3f1abeac9.png">

**Comment by NikkiBytes** [comment]
Can preview at anytime using the toolbar.
