### ISSUE TITLE
Add ability to upload multiple datasets simultaneously

### ISSUE THREAD

**Issue by flaneuse** [biothings/discovery-app#12]
Use case: a user has a bunch of datasets to register in https://discovery.biothings.io/guide/niaid/. Rather than submitting them one by one, it'd be cool to allow users to be able to register multiple simultaneously.

Ideally the inputs would be a .json array or a .csv/.tsv file.

**Comment by NikkiBytes** [comment]
Guide now supports bulk registration of metadata with improved error handling and tools to edit each item.
