### ISSUE TITLE
Feature request: paginate registered datasets on user profile

### ISSUE THREAD

**Issue by flaneuse** [biothings/discovery-app#123]
On https://discovery.biothings.io/dashboard/: only first 10 registered datasets are shown.   Would be nice to paginate to access the others.

<img width="1189" alt="Screen Shot 2022-02-09 at 5 17 39 PM" src="https://user-images.githubusercontent.com/8041065/153318461-2d6ec0ff-984b-48bc-ac50-0a4b120105be.png">
.

**Comment by marcodarko** [comment]
Will be taken care of in PR https://github.com/biothings/discovery-app/pull/140
namespace will be paginated eventually too after a refactor to avoid code duplication, for now namespaces are scrollable since they are expected to be fewer.
