### ISSUE TITLE
"View Source" link on individual class page should link to the class source code

### ISSUE THREAD

**Issue by newgene** [biothings/discovery-app#127]
For example, the "View Source" link on https://discovery.biothings.io/view/schema/Dataset currently points to the full schema file.

![image](https://user-images.githubusercontent.com/130158/154131403-f3a52458-8792-44cc-b3dc-71c18282dd23.png)

It would be better to display the schema definition for the current class only (including its properties).

**Comment by newgene** [comment]
Let's make sure the backend API returns the class definition first.

**Comment by NikkiBytes** [comment]
Working feature has been implemented
