### ISSUE TITLE
Within /dataset page, display the schema used to generate it

### ISSUE THREAD

**Issue by flaneuse** [biothings/discovery-app#13]
e.g. for https://discovery.biothings.io/dataset/dcaab754073ad77b, display that it came from https://discovery.biothings.io/guide/niaid/

**Comment by marcodarko** [comment]
guide meta field has been added to track guide used to generate such metadata, additionally registry supports filtering by guides. Eg. https://discovery.biothings.io/dataset?guide=/guide/niaid
