### ISSUE TITLE
Failure on dataset registry completed through the guide

### ISSUE THREAD

**Issue by flaneuse** [biothings/discovery-app#130]
User reported not being able to register a dataset created using discovery.biothings.io/guide/niaid.  The [metadata](https://github.com/biothings/discovery-app/files/8145161/niaidregistry_mtb.txt) is attached; it seems like a validation error, but I don't see anything obvious wrong with it. 

If there's something actually wrong w/ the metadata, it'd be good to validate earlier and provide a more useful error.  Thx
![Screen Shot 2022-02-25 at 2 12 56 PM](https://user-images.githubusercontent.com/8041065/155810497-a06c70e1-3fbf-440d-b27f-e828983ebc73.png)
!

**Comment by newgene** [comment]
fixed in https://github.com/biothings/biothings_schema.py/commit/439004a6510eb00fc540a4625dd6666c788ee82e and then 1f6d250835cc2ee813b1bb4b171bd87f73c0f3ed
