### ISSUE TITLE
Within /guide, create a link to the datasets that were registered on the DDE with that schema

### ISSUE THREAD

**Issue by flaneuse** [biothings/discovery-app#14]
e.g. for /guide/niaid, display https://discovery.biothings.io/dataset/21d8178fdf22998b, https://discovery.biothings.io/dataset/2aedff2a85b11474, ....

**Comment by andrewsu** [comment]
My suggestion would be to have the "Datasets" link on portal pages (red circle below) go to the specific set of DDE datasets that are relevant.  (Currently, all the "Datasets" links on all portal pages link to the full dataset registry at https://discovery.biothings.io/dataset.)

![image](https://user-images.githubusercontent.com/2635409/95286884-6c5a6480-0819-11eb-89bf-206f3f5e4e68.png)

**Comment by marcodarko** [comment]
Registry filtering has been added and links have been updated to filter datasets by guide eg. https://discovery.biothings.io/dataset?guide=/guide/niaid
