### ISSUE TITLE
add a function to restore ES data from the backup data file

### ISSUE THREAD

**Issue by newgene** [biothings/discovery-app#142]
Currently we backup ES data on daily base and saved to S3:

https://github.com/biothings/discovery-app/blob/master/discovery/utils/backup.py#L78

We should create a store function to restore ES data from this backup file (e.g. populate data for the dev server).

**Comment by newgene** [comment]
Similar implementation from SmartAPI project:

https://github.com/SmartAPI/smartAPI/blob/8454fb2ace68db8a079f028fa351032d57100136/src/admin.py#L97-L121

**Comment by marcodarko** [comment]
@NikkiBytes is this taken care of now? close at your discretion

**Comment by NikkiBytes** [comment]
Working feature implemented!
