### ISSUE TITLE
Teensy feature request: link backwards on schema viewer

### ISSUE THREAD

**Issue by flaneuse** [biothings/discovery-app#145]
This is really dumb, but I would find it useful if the `namespace:ClassWhatever` in the schema viewer page for a particular Class would link back to all the Classes for that particular namespace. So, in this example, `niaid:` would link back to https://discovery.biothings.io/view/niaid. 

I know you have the back button above, but it took me a long time to find it, and given the visual prominence of the namespace:Class title, I think it'd be useful to also use as a back button (similar to how `schema:SoftwareApplication` links to that Class).

<img width="1226" alt="Screen Shot 2022-05-17 at 5 04 45 PM" src="https://user-images.githubusercontent.com/8041065/168931609-8730ea60-8896-4cb3-a839-9e1bf53d9264.png">

**Comment by marcodarko** [comment]
<img width="739" alt="Screen Shot 2022-05-26 at 10 40 04 AM" src="https://user-images.githubusercontent.com/23092057/170546236-724e8c6e-66ae-4602-a556-9323a020fd4a.png">
Will be added soon

**Comment by marcodarko** [comment]
Link to schema home added when hovering over class prefix
