### ISSUE TITLE
Minor feature request: add header to the guides so you know what you're registering

### ISSUE THREAD

**Issue by flaneuse** [biothings/discovery-app#147]
Since there are now two NIAID guides (Dataset, ComputationalTool), it's hard to see what you're registering unless you're careful.  Suggest adding a header and maybe a description to the top (with a link to the /view schema) so it's clear what schema and `@type` you're registering.

<img width="1769" alt="Screen Shot 2022-05-19 at 8 50 56 AM" src="https://user-images.githubusercontent.com/8041065/169343276-7e600824-213e-4afb-b42a-d4eabbd870f0.png">

**Comment by marcodarko** [comment]
A readable header tag was added to the top of each guide. ComputationalTool => Computational Tool
