### ISSUE TITLE
Download functionality & display of more than 10 datasets

### ISSUE THREAD

**Issue by rshabman** [biothings/discovery-app#149]
Hello.  Recommending an ability to select items for download (e.g. into a csv).  Also the function to display more than 10 datasets per page doesn't work for me.  Thank you!  Reed

**Comment by marcodarko** [comment]
Pagination size issues has been resolved, since this issue contains both an issue and a feature request I will close this one and @rshabman feel free to open a new one detailing the desired functionality of the feature you want again so we can consider it, please.

**Comment by marcodarko** [comment]
@rshabman download functionality on the metadata registry has been added ;)
