### ISSUE TITLE
Feature request: suggest someone to bother when a registration fails :)

### ISSUE THREAD

**Issue by flaneuse** [biothings/discovery-app#151]
If a bulk or manual registration fails, most of the times the errors are quite opaque.  As the DDE registration expands beyond just us, it'd be good to have an error also trigger a notification to email the team (aka @marcodarko ).  If we want to get fancy, that would also send info on the data trying to be registered, etc. to help debug.

**Comment by marcodarko** [comment]
A "Get Help" button has been added to error attempts linking directly to an issue template assigned to me.
