### ISSUE TITLE
Minor feature addition: add link to registered dataset on bulk registration

### ISSUE THREAD

**Issue by flaneuse** [biothings/discovery-app#153]
Would nice to also have the link to the registered dataset on the panel on the right side with the green "registered box".  I looked for it there first before finding it in the middle of the table.

<img width="1094" alt="Screen Shot 2022-06-09 at 10 01 46 AM" src="https://user-images.githubusercontent.com/8041065/172903871-112eeb4d-6883-4bdb-a19f-27bbbe712029.png">

**Comment by marcodarko** [comment]
Easy to spot buttons have been added for Update/Registration/Help to last column output message
