### ISSUE TITLE
functionality to allow for individual or bulk item download

### ISSUE THREAD

**Issue by rshabman** [biothings/discovery-app#156]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to download registered dataset metadata into a document for offline analysis (e.g. CSV or xls)

**Describe the solution you'd like**
Check boxes next to datasets with a download function

**Describe alternatives you've considered**
n/a

**Additional context**
at present, critical analysis of the datasets is not easy on the website and requires moving to the data to another analysis platform.  Until a knowledgebase the consumes the NIAID datasets/tools exists, the ability to download will enhance usability as well as broader uptake in the community.

**Comment by marcodarko** [comment]
I've enabled a working version of this feature on the registry, feel free to try it out.  Let me know if you encounter any issues.

**Comment by rshabman** [comment]
Thanks!  The download feature works nicely.  For me I can use the data when it's in a csv format so I can put in excel.  I imagine there is a way to quickly convert?

From: Marco Cano ***@***.***>
Sent: Wednesday, June 15, 2022 5:53 PM
To: biothings/discovery-app ***@***.***>
Cc: Shabman, Reed (NIH/NIAID) [E] ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [biothings/discovery-app] functionality to allow for individual or bulk item download (Issue #156)


I've enabled a working version of this feature on the registry, feel free to try it out. Let me know if you encounter any issues.

-
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbiothings%2Fdiscovery-app%2Fissues%2F156%23issuecomment-1156982652&data=05%7C01%7Creed.shabman%40nih.gov%7C60ad4552c4154073d4ca08da4f196856%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637909267781548182%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=McILVJOYhTCqbKwmeW19hCYsnnsTtFB96TuZpxUX3Ug%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FANOLSYRUPY74PBDLVKVGLVDVPJGDNANCNFSM5YNVJI3Q&data=05%7C01%7Creed.shabman%40nih.gov%7C60ad4552c4154073d4ca08da4f196856%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637909267781548182%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=E9vaF6fgHIn6ep95MeP%2FX6fLBNpg%2B4gJiOU8vz9ucAQ%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and are confident the content is safe.

**Comment by marcodarko** [comment]
I'll look into it and add it as an option if I can get good results. TY!

**Comment by rshabman** [comment]
Thanks!  Really appreciate you looking into this.

Reed

From: Marco Cano ***@***.***>
Sent: Wednesday, June 15, 2022 6:14 PM
To: biothings/discovery-app ***@***.***>
Cc: Shabman, Reed (NIH/NIAID) [E] ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [biothings/discovery-app] functionality to allow for individual or bulk item download (Issue #156)


I'll look into it and add it as an option if I can get good results. TY!

-
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbiothings%2Fdiscovery-app%2Fissues%2F156%23issuecomment-1157003992&data=05%7C01%7Creed.shabman%40nih.gov%7C6751aeace5254d77185608da4f1c4b54%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637909280182063271%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2FAmfWoh2ml8MVrQta7TQPmLR6fdEZkfbSJulzQdA1kY%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FANOLSYUBSFVTV6VRBIUTV5TVPJIQZANCNFSM5YNVJI3Q&data=05%7C01%7Creed.shabman%40nih.gov%7C6751aeace5254d77185608da4f1c4b54%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637909280182063271%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=hB1Frbbk2hvRptD23K%2Ft9A3M0lJl%2FpxdNmpecGCepXw%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and are confident the content is safe.

**Comment by marcodarko** [comment]
@rshabman feature has been added.  Please note that since we have multiple levels of nesting some paths will be flattened.  Check it out, hopefully this takes care of this issue for you!

**Comment by rshabman** [comment]
This is great, thank you!  Will make it easier to analyze what's uploaded.

Thanks again for working on this feature.

Reed

From: Marco Cano ***@***.***>
Sent: Friday, June 17, 2022 1:49 PM
To: biothings/discovery-app ***@***.***>
Cc: Shabman, Reed (NIH/NIAID) [E] ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [biothings/discovery-app] functionality to allow for individual or bulk item download (Issue #156)


@rshabman<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frshabman&data=05%7C01%7Creed.shabman%40nih.gov%7Cde34c6486456479bc96a08da5089bd7f%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637910849775538586%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=tJ48Auy%2FpMcd4K0WD4QzphluID2ilUrSGc0u6%2BHoRmk%3D&reserved=0> feature has been added. Please note that since we have multiple levels of nesting some paths will be flattened. Check it out, hopefully this takes care of this issue for you!

-
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbiothings%2Fdiscovery-app%2Fissues%2F156%23issuecomment-1159107434&data=05%7C01%7Creed.shabman%40nih.gov%7Cde34c6486456479bc96a08da5089bd7f%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637910849775538586%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=AeMW92caxQtAtLWAB3eQ1zjVvUQrrUni4%2FxVGJQmSg8%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FANOLSYVKX52MUU4JPOJPA3DVPS3CRANCNFSM5YNVJI3Q&data=05%7C01%7Creed.shabman%40nih.gov%7Cde34c6486456479bc96a08da5089bd7f%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637910849775694774%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=XEnlk1RbZSDWWNq%2BU5TyZRhD4H3FE9NS%2FPU1c9ex8Ao%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and are confident the content is safe.

**Comment by flaneuse** [comment]
@marcodarko @rshabman point #2 is captured in ticket #150.

**Comment by marcodarko** [comment]
@rshabman if you wanna open an issue for point 1 that would be great, add some details on how I can reproduce the issue so I can see if it's UI issue or not. (I did try it on my end but I do see create separate rows so I wanna see how I can replicate this bug).
Feel free to suggest any ideas on how I can make the UI more useful to you so I can take that into consideration.

**Comment by rshabman** [comment]
@marcodarko - i just tried again and this time when i download it looks good.  So please close the ticket and thanks for creating this functionality!  I will open a new ticket if/when i have additional suggestions for this tool since it's important for me as i capture the landscape of these data.
