### ISSUE TITLE
Quick edit functionality seems to be pulling the wrong schema

### ISSUE THREAD

**Issue by flaneuse** [biothings/discovery-app#16]
When I try to edit a [dataset's metadata](https://discovery.biothings.io/api/dataset/49987e7de91ba27e), for instance to fix `author.affiliation` to make it an object, I get a validation error that `creator` is a required field.  According to the [schema](https://discovery.biothings.io/view/outbreak/Dataset), `creator` isn't required: `author` is.  Maybe pulling the incorrect schema for validation?

error message:
```
'creator' is a required property
Hint: name,description,creator,publisher,identifier
```

**Comment by marcodarko** [comment]
WIP Specified which schema to use with each request. Temporary fix for now assumes prefix is also the namespace registered, if that is the case you should be ok.  Will collect additional metadata to point to the correct schema/namespace.

**Comment by NikkiBytes** [comment]
Bug is fixed, issue is resolved.
