### ISSUE TITLE
Add search bar to registered datasets

### ISSUE THREAD

**Issue by flaneuse** [biothings/discovery-app#160]
**Describe the solution you'd like**
When you've registered a ton of datasets, it's hard to find a specific one in the registered list, if you want to edit it.  Would be nice to add a search bar.

<img width="932" alt="Screen Shot 2022-06-13 at 11 04 12 AM" src="https://user-images.githubusercontent.com/8041065/173417402-49eccee3-01b0-47de-b66b-8a403f3e26e1.png">

**Comment by marcodarko** [comment]
You can search using the query endpoint now which also supports field queries
