### ISSUE TITLE
Enable editing of property descriptions in validation editor

### ISSUE THREAD

**Issue by gtsueng** [biothings/discovery-app#163]
**Is your feature request related to a problem? Please describe.**
A bioschema profile can be a subclass of a schema.org type and may have a more nuanced description for what a property should be used for in the profile. Currently, the only way to add these nuances is to edit the $validation in json file directly. To be clear, we want the property description in the $validation to reflect these nuances, NOT add these nuances to the actual, pre-existing schema definitions of existing properties. For example, bioschemas might have additional description for the property "additionalType" for a bioschemas profile. We want to capture that for that particular profile in the $validation: additionalType: description, NOT elsewhere

**Describe the solution you'd like**
Create a button or checkbox under "{property name} (x)" called "edit description" for each property, which enables them to edit the value for the "description" of the property in the validation editor 
![image](https://user-images.githubusercontent.com/9200138/173647507-0dd5d9c2-1709-45dc-9f4d-d8178c7f7da2.png)
 
**Describe alternatives you've considered**
Bypass the DDE and just work with the json file--otherwise, you make the changes in the DDE, then have to go back and edit each property in the exported jsonld.

**Additional context**

**Comment by gtsueng** [comment]
Viable work-around is to create a new validation rule (via the validation rule editor) which includes 'description': < special description > which can be drag-n-dropped to the property and will overwrite the existing 'description'.

**Comment by marcodarko** [comment]
I've added this option, tho you may need to clear your cache to load the new option.  PS just remember you can create any new objects as options on your editor to fit your needs, any properties with the same key name will just override each other. This is basically what's happening here. So basically that option was already there but now it's an out of the box option, perhaps useful for new users.
