### ISSUE TITLE
modifications to Discovery Guide

### ISSUE THREAD

**Issue by andrewsu** [biothings/discovery-app#17]
Currently, the "Discovery Guide" link in the header goes to https://discovery.biothings.io/best-practices.  A few possible suggestions:

1) Is `/best-practices` the best location for this page?  "Best practices" and "Discovery Guide" seem like two different things...

2) At the top of that page, perhaps have a short text description of what a "Discovery Guide" is (not obvious from that phrase alone).  Basically explain that it is a wizard that allows dataset registration according to a given schema.

3) Now that we have three guides, have links on this page to all three of them

**Comment by marcodarko** [comment]
We have renamed the sections available and added more descriptions through the DDE and added data portal pages to further organize our content. We have taken multiple actions to make the content easier to navigate and make the workflow from creating a schema to registration more simplified and easier to navigate. Please take a look and feel free to open an issue if there's more specific requests or problems.
