### ISSUE TITLE
[Minor feature request] Add case-insensitive searching within the Schema Editor

### ISSUE THREAD

**Issue by flaneuse** [biothings/discovery-app#188]
**Describe the solution you'd like**
In https://discovery.biothings.io/editor, if I search for a property within a schema, the searching is cased. For instance, if I want to find `inLanguage`, searching for `language` won't work (but `Lang` will).  Would be nicer if this searching was case insensitive.
<img width="1010" alt="Screen Shot 2022-09-12 at 2 21 30 PM" src="https://user-images.githubusercontent.com/8041065/189761390-0cef2043-bc40-4095-b00a-1cb4be1a45f3.png">

<img width="991" alt="Screen Shot 2022-09-12 at 2 21 40 PM" src="https://user-images.githubusercontent.com/8041065/189761396-74340e61-8186-472a-badc-9af0b947fead.png">

**Comment by marcodarko** [comment]
Will be included in the next update.
