### ISSUE TITLE
[Improvement] Improve sort order for datasets in the registry

### ISSUE THREAD

**Issue by flaneuse** [biothings/discovery-app#189]
**Is your feature request related to a problem? Please describe.**
The default sort order for the registry seems off.  If I search for the name of a particular dataset (e.g. `Mouse cortex lipidome response to West Nile Virus`), I would expect the dataset that contains that exact phrase to be the top result.  Instead, it's buried at the bottom.

**Describe the solution you'd like**
Are you sorting by `_score`?  It seems like this result should be listed first.  You might also consider changing the default search behavior to combine terms by `AND` rather than `OR`.

<img width="934" alt="Screen Shot 2022-09-12 at 5 20 27 PM" src="https://user-images.githubusercontent.com/8041065/189780888-a8012583-eb8e-4fce-a18f-bba0ad0fac65.png">

**Comment by marcodarko** [comment]
phrase match priority added and boosted for datasets. Also for schemas case insensitivity added for improved results.
