### ISSUE TITLE
Bug: Attempting to derive a new schema from a non-schema.org schema throws a validation error.

### ISSUE THREAD

**Issue by gtsueng** [biothings/discovery-app#19]
Using the DDE playground to create a new schema seems to work fine when 'extending' it from a schema.org class.  The schema generated in the preview can be saved to github, loaded into the schema playground and correctly visualized. [Example schema](https://github.com/gtsueng/schemas/blob/fix_validation/N3C/schema-derived_autogen.json).

This is not the case when you try to extend from a (non-schema.org) schema registered in the DDE playground such as the outbreak schema or even the BioMedicalDataset schema. [Example 1: bte:BioMedicalDataset schema-derived class](https://github.com/gtsueng/schemas/blob/fix_validation/N3C/bteBioMedicalDataset-derived.json). [Example 2: outbreak:Dataset schema-derived class.](https://github.com/gtsueng/schemas/blob/fix_validation/N3C/autogenvalidation.json)

The new schemas created from the registered class will give the following error when you try to load them. "Failed because:
field about in $validation is not correctly documented"
![image](https://user-images.githubusercontent.com/9200138/93816064-d2d16700-fc0b-11ea-8444-a139fc386df9.png)

**Comment by gtsueng** [comment]
Just found out that extending from non-schema.org classes is currently not supported.  Suggest restricting the search options (to extend) to only schema.org classes if that's the case so that the user does not spend time extending from a non-schema.org class to create a new schema that will ultimately fail in the schema playground.

**Comment by marcodarko** [comment]
Going to mark as duplicate as it's the same issue as here: https://github.com/biothings/discovery-app/issues/4

Currently our backend does not support registering schemas derived from non-schema.org subclasses YET. In order to do this we need to keep track of versions, and we will support that in the future. For any further updates please refer to the issue above.
