### ISSUE TITLE
preload cardinality when available

### ISSUE THREAD

**Issue by gtsueng** [biothings/discovery-app#196]
**Is your feature request related to a problem? Please describe.**
When extending from NIAID schema (which has cardinality encoded via `owl:cardinality`, and the cardinality toggle is enabled, preload the existing cardinality from the parent schema so that it's easy to see right away. Here, you can see the cardinality selector is empty even though the parent class has a cardinality information saved for the property:
![image](https://user-images.githubusercontent.com/9200138/192376050-bd71dab7-2b80-46da-9516-2bb263c70663.png)

**Describe the solution you'd like**
Have the cardinality preloaded if user toggles the cardinality editor. So in the previous example, it would look like this by default:
![image](https://user-images.githubusercontent.com/9200138/192376392-d8a5b401-b6ea-46af-902e-0e88119b6606.png)

**Describe alternatives you've considered**
Ask users to scroll through the preloaded validation rules, identifying the `owl:cardinality` portion and selecting a cardinality based on the value. But, the preloaded json validation rules are working nicely--seems like preloading this makes sense.

**Comment by marcodarko** [comment]
@gtsueng is there a class in any of the namespaces that has cardinality like this already? I wanna test this feature.

**Comment by flaneuse** [comment]
NIAID and NDE should.

**Comment by marcodarko** [comment]
Cardinality is not preloaded when available automatically.
