### ISSUE TITLE
[Feature Request] Add description to registered schemas

### ISSUE THREAD

**Issue by flaneuse** [biothings/discovery-app#197]
**Describe the solution you'd like**
Feature request from NIAID on the Registered Schema viewer page: `Could you add NIAID Data Ecosystem somewhere on the [page](https://discovery.biothings.io/view/nde), instead of “nde” so that it is more clear that a user is in the right place? `. It'd be good to have the description of the schema, as well as maybe a bit more context about WHAT this page is (e.g. it's a registered schema, etc.).

**Additional context**
Can you just pull from `rdfs:comment` to grab the user-supplied description of the schema?
<img width="1125" alt="Screen Shot 2022-10-05 at 12 10 34 PM" src="https://user-images.githubusercontent.com/8041065/194143461-a10e5f2f-e05d-4f1d-9ea9-11763bc293a2.png">

**Comment by marcodarko** [comment]
@flaneuse did you mean a description for the whole namespace or description for each class? I don't think we have one for the whole schema right? I can certainly add the "comment" per class

**Comment by flaneuse** [comment]
I was suggesting adding a description for the namespace (whole schema) to `/view`: https://discovery.biothings.io/view/nde.  You already have a description of the Class on the class page, which I think makes sense.

You already collect a description for the entire namespace, which is stored in [["@graph"]["rdfs:comment"]](https://raw.githubusercontent.com/NIAID-Data-Ecosystem/nde-schemas/main/NDE_schema.jsonld):

```
"rdfs:comment": "Datasets contained in the NIAID Data Ecosystem. The NIAID Data Ecosystem is a secure environment to find, access and analyze immune-mediated and infectious disease data and computational tools to speed the development of diagnostics, therapeutics, and vaccines. The NIAID Data Ecosystem Discovery Portal harvests metadata from dataset repository and harmonizes them to this schema to enable easy cross-platform dataset searching and filtering."
```

**Comment by flaneuse** [comment]
Sorry, I'm wrong-  that's the description for the Class.

**Comment by marcodarko** [comment]
A hardcoded description is now available for "nde", in the future we will have to implement a way to save that to the DDE document.
