### ISSUE TITLE
keyword search in dataset registry not behaving as expected

### ISSUE THREAD

**Issue by andrewsu** [biothings/discovery-app#21]
There are currently 39 datasets in the dataset registry (https://discovery.biothings.io/dataset).  When I search "snohomish", I expect to get only one data set back (https://discovery.biothings.io/dataset/220edb57fb41eeea). The discovery app correctly highlights that dataset, but the API is currently returning all 39 (https://discovery.biothings.io/api/dataset?q=snohomish)

![image](https://user-images.githubusercontent.com/2635409/95286543-7465d480-0818-11eb-94f3-4d1bde958aae.png)

**Comment by marcodarko** [comment]
We added an additional BioThingsHandler to handle queries on the dataset endpoint, previously only one index (schema) could handle queries, and this endpoint always returned everything no matter what. Queries should now work just like on any other BT app like so: https://discovery.biothings.io/api/dataset/query?size=1000&q=covid
