### ISSUE TITLE
Enable markup generation support

### ISSUE THREAD

**Issue by gtsueng** [biothings/discovery-app#211]
**Is your feature request related to a problem? Please describe.**
Right now it can be challenging to figure out how structure metadata so that it will successfully validate against a DDE-registered schema. For example, if I have a protein record, it's hard for someone who is not familiar with JSON-schema/JSON-LD to figure out how to structure their metadata.

**Describe the solution you'd like**
Enable the metadata submission form (used by NDE, NIAID, etc.) such that users can use the form to generate and save a metadata JSON-LD file (as opposed to submitting it to our APIs)

**Describe alternatives you've considered**
Bioschemas has a markup generation tool, but it is not expected to be maintained and may be disabled towards Q3 2023

**Comment by marcodarko** [comment]
Could you please send me a link to this tool, curious how it works

**Comment by gtsueng** [comment]
Not sure it's even working anymore, but: https://www.macs.hw.ac.uk/SWeL/BioschemasGenerator/

**Comment by gtsueng** [comment]
Here's the one for codemeta (a different project): https://codemeta.github.io/codemeta-generator/

**Comment by gtsueng** [comment]
The markup generator on Dev is so cool! My only suggestion is to put the required fields at the top of the form and optional ones at the bottom
