### ISSUE TITLE
Store and display the status of the daily schema update routine

### ISSUE THREAD

**Issue by newgene** [biothings/discovery-app#213]
Daily schema update has been updated in this commit: 09e6e1e397fe03bd035c141dcd4ce29abe729e97. Now we can store the status information about each schema update too and display it on the web UI.

Similar in SmartAPI application, we can store this information under the `_status` metadata field of a schema object:

```
"_status": {
    "refresh_status": 200,
    "refresh_ts": "2022-12-06T08:02:19+00:00"
}
```

**Comment by NikkiBytes** [comment]
This featured has been implemented/merged with working tests, not sure if it is in development stage yet...

**Comment by NikkiBytes** [comment]
Complete.
