### ISSUE TITLE
clarify CViSB portal vs NIAID portal

### ISSUE THREAD

**Issue by andrewsu** [biothings/discovery-app#22]
The "branding" on https://discovery.biothings.io/portal/cvisb is a little muddled because we mix up CViSB and NIAID.  Currently low priority, but at some point we should make that clearer...

![image](https://user-images.githubusercontent.com/2635409/95287213-2a7dee00-081a-11eb-90bd-836a90aa573c.png)

**Comment by flaneuse** [comment]
@marcodarko: proposed changes to make:

1. https://discovery.biothings.io/portal/cvisb --> https://discovery.biothings.io/portal/niaid (portals.html)
2. Portal logo to NIAID logo, not CViSB logo (portal.html: `image`, portals.html: `image`)
3. portal.html: switch statement to `niaid` not `cvisb`
4. Nav dropdown: change link to NIAID (href, <a> content) (header.html)
5. In guides.html: change it to:
    -  "Data Portal | NIAID"
    - Update link to /portal/niaid
    - Change logo to elephant NIAID logo
    - description: 
```
<b>National Institute of Allergy and Infectious Diseases (<a href="https://www.niaid.nih.gov/" target="_blank" rel="nonreferrer">NIAID <i class="fas fa-external-link-alt"></i></a>)</b> (<a href="https://discovery.biothings.io/niaid/" target="_blank" rel="nonreferrer">NIAID Data Portal <i class="fas fa-external-link-alt"></i></a>) dataset metadata based on this <a href="/view/niaid/" target="_blank" rel="nonreferrer">schema <i class="fas fa-external-link-alt"></i></a> structure.
```
6. schema.py has a ref to cvisb but I'm not sure where that's used.

**Comment by marcodarko** [comment]
Branding has been updated through the website.  Mention on schema.py is just an example comment for data shape, all good there.
