### ISSUE TITLE
Sort/Ranking Feature

### ISSUE THREAD

**Issue by NikkiBytes** [biothings/discovery-app#220]
When searching for a class (i.e. ComputationalTool), in the [registry](https://discovery.biothings.io/registry) , currently the results are sorted without any rank or relevance.

It would useful to apply a sort/rank to the results displayed. If we capture the **usage data,** we can sort classes based on _how frequently they are extended_ throughout other schemas, and then display the results showing the "most extended" classes first.  

Due to the possible depth of "class inheritance" to capture, one suggestion is to possibly use only one level of "extension" and keep a "frequency list" of the class count to reference. We would run an initial coverage, then add a function to update the coverage as new classes are added.

**Comment by NikkiBytes** [comment]
<img width="1283" alt="Screen Shot 2024-09-25 at 1 36 14 PM" src="https://github.com/user-attachments/assets/1a40685d-7ad4-45d0-951e-89a73cd25e12">
We noticed the case sensitivity is effecting the results, i.e. "Dataset" vs. "dataset"

**Comment by marcodarko** [comment]
Usage is not large enough to implement this feature.  We will reconsider at a later time.
