### ISSUE TITLE
GitHub urls for json not getting resolved to raw json files

### ISSUE THREAD

**Issue by gtsueng** [biothings/discovery-app#227]
**Describe the bug**
I only consider this a bug because it wasn't an issue before. In the previous production version of the DDE, when you pasted a GitHub url of the JSON into the viewer, it would pop-up a clarification to use the raw version of the url (as opposed to the html version). This functionality doesn't appear to be working in the new DDE so the viewer will report an error when looking at something like https://github.com/gtsueng/specifications/blob/master/ChemicalSubstance/jsonld/ChemicalSubstance_v0.5-DRAFT.json instead of https://raw.githubusercontent.com/gtsueng/specifications/master/ChemicalSubstance/jsonld/ChemicalSubstance_v0.5-DRAFT.json

**To Reproduce**
* In FireFox or Edge go to the DDE Schema playground
* Click on the url input field for the schema viewer
* Paste: https://github.com/gtsueng/specifications/blob/master/ChemicalSubstance/jsonld/ChemicalSubstance_v0.5-DRAFT.json
At this point a pop-up would suggest using the url for the raw version (in the previous DDE schema playground viewer), but it doesn't happen here
* Click "Let's go" and get an error about the schema (but the schema is fine, it's just that the DDE is trying to look at the schema with html markup from GitHub instead of the raw schema file

**Expected behavior**
It should pop-up the GitHub url resolver/check dialog box as it did before

**Screenshots**

**Additional context**
This is one of those features that get taken for granted. When it works, you don't notice it. When it doesn't, it can send the user into a spiral trying to correct a JSON file which is perfectly fine.

**Comment by marcodarko** [comment]
Will be fixed soon! A minor change to a library used and how a method should be called and was outdated caused a small bug. No major testing needed so pushing straight to prod and dev.

**Comment by marcodarko** [comment]
Fix deployed
