### ISSUE TITLE
[API backend] Support filtering for schema classes with validation rules

### ISSUE THREAD

**Issue by newgene** [biothings/discovery-app#230]
The current registry query API:

https://discovery.biothings.io/api/registry/query?q=dataset&meta=1

does not allow filtering for classes including validation rules. Although we don't need to index the particular validation object fields, a quick filter for existence of `validation` field would be handy to have.

This likely requires an index mapping change, currently `validation` is skipped for indexing as a whole:

https://github.com/biothings/discovery-app/blob/7d7a81ceff50e31db715840953d1dac86c254fc3/discovery/model/schema.py#L174C39-L174C39

**Comment by newgene** [comment]
a use case would be #229

**Comment by NikkiBytes** [comment]
Feature complete, added to main.
