### ISSUE TITLE
New property deleted when editing another

### ISSUE THREAD

**Issue by ljgarcia** [biothings/discovery-app#238]
**Describe the bug**
New property is deleted on edit click.

**To Reproduce**
1. Load a saved progress
2. Click on the option "edit" for a new property
3. The new property is deleted and open in the editor

**Expected behavior**
I expect the new property to be opened for edition without deleting it. The deletion forces me to `submit` again which seems an unnecessary step.

**Screenshots**

**Additional context**
I observed this behavior when loading a work in progress. I do not recall this to happen the first time working on a new type.

**Comment by marcodarko** [comment]
This should be resolved in the next update but will test again one deployed.  Some authetication issues don't allow me to say for sure yet but will post an update ASAP
