### ISSUE TITLE
Add close without saving option to new property editing window

### ISSUE THREAD

**Issue by ljgarcia** [biothings/discovery-app#240]
**Is your feature request related to a problem? Please describe.**
I click on the option to edit a new property that I am creating in the type editor. I realize all is good with it. I would like to close without saving rather I have to submit again.

**Describe the solution you'd like**
I would like to see an X icon on the top right of the property editing window.

**Describe alternatives you've considered**
Click on the submit button is the only option now (but there is a bug with the domain, see https://github.com/biothings/discovery-app/issues/239)

**Additional context**

**Comment by marcodarko** [comment]
This will be updated soon, with the ability to update and cancel actions.
