### ISSUE TITLE
Change URL for an existing namespace

### ISSUE THREAD

**Issue by ljgarcia** [biothings/discovery-app#241]
**Describe the bug**
Change URL for an existing namespace does not seem to do anything.

**To Reproduce**
1. Go to a used dashboard
2. Click on the update button for any registered namespace
3. On the pop up window choose "Change URL"
4. On the text box fill in the new link
5. Click "Go"
6. Nothing happens

**Expected behavior**
On the last step, I would expect to see something similar to what happen on the playground "Visualize your own schema", i.e., a mini report on whether the schema link could be loaded and whether it looks good and ready to go.  If it is all clear, I would expect the namespace to be updated to the new link.

**Screenshots**

**Additional context**

**Comment by ljgarcia** [comment]
Using developer tools on the browser, this is what I see
```
 SweetAlert2: "allowOutsideClick" parameter requires `backdrop` parameter to be set to `true`
c @ _nuxt/entry.971e7970.js:1559
Sb @ _nuxt/entry.971e7970.js:1617
_main @ _nuxt/entry.971e7970.js:1620
oo @ _nuxt/entry.971e7970.js:1620
Im @ _nuxt/entry.971e7970.js:1617
(anonymous) @ _nuxt/index.b91b0c88.js:1
Promise.then (async)
then @ _nuxt/entry.971e7970.js:1620
updateSelected @ _nuxt/index.b91b0c88.js:1
onClick @ _nuxt/index.b91b0c88.js:1
Ac @ _nuxt/entry.971e7970.js:1
Ga @ _nuxt/entry.971e7970.js:1
i @ _nuxt/entry.971e7970.js:1
_nuxt/index.b91b0c88.js:1 Uncaught (in promise) ReferenceError: data is not defined
    at _nuxt/index.b91b0c88.js:1:8271
```

**Comment by marcodarko** [comment]
@ljgarcia Hi, yes some libraries were updated during our migration and I think I missed that, I will try to push an update ASAP since it's an easy fix.  Also working on all the other issues just FYI.  Thank you!
