### ISSUE TITLE
Link to ranges in the schema viewer are incorrect

### ISSUE THREAD

**Issue by ljgarcia** [biothings/discovery-app#245]
**Describe the bug**
Link to ranges in the schema viewer are incorrect

**To Reproduce**
1. Go to https://discovery.biothings.io/ns/maSMP/maSMP:Question (or any other type in a schema)
2. Click on any of the expected types for a property
3. All expected range properties link to the page itself (in this case https://discovery.biothings.io/ns/maSMP/maSMP:Question)

**Expected behavior**
I would expect property ranges to link to the actual pages as defined in the jsonld file. For the example:
* rdf:Statement should link to http://www.w3.org/1999/02/22-rdf-syntax-ns#Statement
* schema:DefinedTerm should link to https://schema.org/DefinedTerm
* schema:PropertyValue should link to https://schema.org/PropertyValue

**Screenshots**

**Additional context**

**Comment by marcodarko** [comment]
Pushing all fixes to prod now, feel free to close or comment on the issues if there's anything else.

**Comment by ljgarcia** [comment]
Working fine with the exception of schema:Text
