### ISSUE TITLE
[NDE submission portal] Remove coverage from NDE portal

### ISSUE THREAD

**Issue by gtsueng** [biothings/discovery-app#249]
**Is your feature request related to a problem? Please describe.**
The NIAID team found the coverage information confusing and would like it removed from the NIAID Data Ecosystem portal on the DDE

**Describe the solution you'd like**
Remove what's in the circle here:
![image](https://github.com/biothings/discovery-app/assets/9200138/b1e87794-1171-49fb-835a-a693dbccbb51)

**Describe alternatives you've considered**
Alternatively hide it so it can't be seen

**Additional context**

**Comment by marcodarko** [comment]
Coverage is now hidden for these portals, settings were added to each portal config to decide if you wanna show this link or not.
