### ISSUE TITLE
[NDE submission portal] Enable filtering by NDE records

### ISSUE THREAD

**Issue by gtsueng** [biothings/discovery-app#250]
**Is your feature request related to a problem? Please describe.**
![image](https://github.com/biothings/discovery-app/assets/9200138/9a8996e3-e739-4a67-b2e9-824cffa89a8e)
Currently the DDE data registry browser allows segmenting of the records by those ingested via other portals, but not NDE (eg the interactive `NIAID:Dataset`, `outbreak:Dataset` tags in the image)

**Describe the solution you'd like**
Enable filtering by `NDE:ResourceCatalog`

**Describe alternatives you've considered**
I tried editing the example tags to make them work, but it didn't work.

**Comment by marcodarko** [comment]
Filters added for NDE:ResourceCatalog! We can add other if necessary just let me know as these need to be added manually.
