### ISSUE TITLE
error on dataset registration

### ISSUE THREAD

**Issue by andrewsu** [biothings/discovery-app#27]
I got to this error state when I click the "Register" button:

| ![image](https://user-images.githubusercontent.com/2635409/95766776-99b77000-0c68-11eb-80aa-1e9542ff721b.png) |
| --- |

This is what I filled out for required fields (left all recommended ones blank):

![image](https://user-images.githubusercontent.com/2635409/95766912-d3887680-0c68-11eb-93b9-4ed4787a36d4.png)

Currently, it looks like there is a "silent" error -- I would expect that any issue would be flagged in the web interface...

**Comment by marcodarko** [comment]
Fixed the issue where required field were just merged with no duplicate check, now only required fields not included in the main Class' required list are added. This fixes the validator being broken by duplicates on data/required.
