### ISSUE TITLE
dataset registration form improvements

### ISSUE THREAD

**Issue by andrewsu** [biothings/discovery-app#28]
I have two suggestions to improve the dataset registration form:

* Form asks for "The identifier of the dataset **if available**", but it's a required field and the form won't allow moving on unless that's filled.  So suggest removing "if available".
* It is unclear what "Reusable person definition" means.  

![image](https://user-images.githubusercontent.com/2635409/95771337-b60adb00-0c6f-11eb-9e6a-d0e3ec0f789c.png)

**Comment by marcodarko** [comment]
We have reworded the identifier field and made sure to update other guides to make sure identifier is required on all. We have also fixed the issue where the field description was being overwritten by a duplicate key for creator.
