### ISSUE TITLE
loading existing metadata should clear the required field error msg

### ISSUE THREAD

**Issue by newgene** [biothings/discovery-app#29]
To reproduce:

1. go to a guide form
2. "Import Metadata" --> "Metadata by you registered here" --> select a dataset
3. required field values should have pre-filled, but the "required field" error still there. These error msgs should be cleared.

![image](https://user-images.githubusercontent.com/130158/95789922-44448880-0c93-11eb-8d43-cbf82f661476.png)

**Comment by marcodarko** [comment]
Added a call to the validator after import to properly update the guide issues to the newest state. All fields should update now.
