### ISSUE TITLE
Schema's hierarchy view not rendering for n3c namespace

### ISSUE THREAD

**Issue by newgene** [biothings/discovery-app#291]
**Describe the bug**

**To Reproduce**
1. go to schema registry
2. select n3c namespace
3. click "Change View" to its hierarchy view

**Expected behavior**
A tree-like view. 

**Screenshots**
<img width="585" alt="image" src="https://github.com/user-attachments/assets/7f58df7e-f9f4-4d24-aac0-6c9645e6ef7d">

**Additional context**
For other schemas with different namespaces, this view renders just fine.

**Comment by marcodarko** [comment]
Will be addressed in https://github.com/biothings/discovery-app/pull/292
