### ISSUE TITLE
N3C portal's dataset view includes other datasets

### ISSUE THREAD

**Issue by newgene** [biothings/discovery-app#293]
**Describe the bug**
N3C portal's dataset view shows dataset records from other portals

**To Reproduce**
Portal --> N3C --> Datasets

**Expected behavior**
Should be only N3C-specific datasets

**Screenshots**
None.

**Additional context**
None.

**Comment by marcodarko** [comment]
Will be addressed in https://github.com/biothings/discovery-app/pull/292

**Comment by marcodarko** [comment]
issue fixed due to some renaming and deployed!
