### ISSUE TITLE
ProxyHandler should be deprecated now?

### ISSUE THREAD

**Issue by newgene** [biothings/discovery-app#294]
I noticed when we run `python index.py --debug`, it requires to have a nodejs UI server running at `localhost:3000` via the `ProxyHandler`. It's probably a temp solution back then. If confirmed we don't need it any more, let's remove it, so that `--debug` mode can run properly.

https://github.com/biothings/discovery-app/blob/41b9f8c70ac79ecef7bf8c13786aea272c9d40e5/index.py#L51-L54

**Comment by marcodarko** [comment]
Will be addressed in PR https://github.com/biothings/discovery-app/pull/295

**Comment by marcodarko** [comment]
Removed and updated!
