### ISSUE TITLE
passing browser validation but failing server validation

### ISSUE THREAD

**Issue by andrewsu** [biothings/discovery-app#30]
![2020-10-20_10-38-57](https://user-images.githubusercontent.com/2635409/96623761-b125d700-12c0-11eb-9e42-bb1cf7f1798e.png)
![2020-10-20_10-38-20](https://user-images.githubusercontent.com/2635409/96623767-b2ef9a80-12c0-11eb-839a-3fb01061dee6.png)

**Comment by marcodarko** [comment]
We have updated the schema to reflect this requirement by our backend. Now identifier is marked as required and updated on our site.
