### ISSUE TITLE
use an already-registered dataset as a template

### ISSUE THREAD

**Issue by andrewsu** [biothings/discovery-app#34]
Something like "create a new dataset record like this".  Not sure whether to display that on the existing dataset details page, or have a dataset selector on the dataset registration page, or something else...  This can be accomplished by downloading and importing the JSON, so this would be an easier way of accomplishing that...

**Comment by newgene** [comment]
This is pretty much covered with the existing "import metadata" feature from a registration form:

![image](https://user-images.githubusercontent.com/130158/96771237-3fb85800-1396-11eb-9f9b-542805144ad3.png)

But the feature is a bit hidden right now.

**Comment by andrewsu** [comment]
Short-term, I suggest changing the wording there.  Something like "Copy metadata from an existing dataset" would be clearer to me, I think...

**Comment by marcodarko** [comment]
Wording has been changed to "Copy metadata from an existing dataset authored by you" with additional warning text under to let you know about repercussions of changing field "identifier", Additional documentation on guide usage will be created on a separate issue.
