### ISSUE TITLE
Improve controlled vocabulary selection

### ISSUE THREAD

**Issue by flaneuse** [biothings/discovery-app#36]
Suggestion from 2020-10-20 DDWG working group meeting.

When one enters a term that has a lot of hits, it's really hard to find what you're looking for in the long list of matching terms.  For instance: if you enter "influenza a" for "infectiousAgent" in the NIAID dataset schema, the terms are cut off (since they're long):
<img width="439" alt="Screen Shot 2020-10-20 at 1 17 32 PM" src="https://user-images.githubusercontent.com/8041065/96627777-3364ca00-12c6-11eb-9cfc-adafcef75273.png">

Suggest:

1. Sorting the list by best match first; it looks like spaces are getting split in some cases (sorry, don't have an example), so you're getting partial matches for things like "influenza"
2. Add a search box at the top to filter the results.  For instance, if you typed "Washington", it'd only give you things like "Influenza A virus (A/Washington2958/2012(H1N1))"

**Comment by marcodarko** [comment]
Updated component for ontology term selection that supports multiple query, cart, preview and filtering.
<img width="458" alt="Screen Shot 2021-01-26 at 2 51 48 PM" src="https://user-images.githubusercontent.com/23092057/105916603-0a9b5180-5fe6-11eb-841e-48ea8de4b755.png">
