### ISSUE TITLE
Improve display of objects in Guide

### ISSUE THREAD

**Issue by flaneuse** [biothings/discovery-app#37]
1. In the Guide, sometimes the description of the property isn't listed for nested objects, e.g. for NIAID dataset:
<img width="554" alt="Screen Shot 2020-10-20 at 1 36 10 PM" src="https://user-images.githubusercontent.com/8041065/96629467-7e7fdc80-12c8-11eb-8ef1-210bd6874833.png">
<img width="564" alt="Screen Shot 2020-10-20 at 1 35 09 PM" src="https://user-images.githubusercontent.com/8041065/96629478-817acd00-12c8-11eb-809c-661c471b7b8a.png">
... and sometimes the description is given:
<img width="560" alt="Screen Shot 2020-10-20 at 1 36 05 PM" src="https://user-images.githubusercontent.com/8041065/96629501-8ccdf880-12c8-11eb-88b7-6445c4553b6a.png">

2. Add asterisks or similar to make explicit which properties are required for objects within a schema (e.g. `funder.name`, `identifier` are required; rest are optional for `NIAID:funding`)

3. Specify the parent object in the field name somehow.  For instance, NIAID has two descriptions: `description` and `funding.description`.  When filling in the funding description, some users were confused about whether that was referring to the dataset description or the funding description

Based off of feedback from 2020-10-20 NIAID DDWG call.

**Comment by marcodarko** [comment]
![Screen Shot 2020-10-20 at 2 03 55 PM](https://user-images.githubusercontent.com/23092057/96644088-6797b500-12dd-11eb-9bac-bb7e3da292fd.png)

Made some changes for now, I'll see if there's any additional improvements I can make

**Comment by marcodarko** [comment]
Modal view is now replaced by a better intake form that addresses multiple issues and allows for addition of multiple nested objects, sorting, and marking of requirements.
