### ISSUE TITLE
Bug: new property on an extended schema throwing error when trying to visualize

### ISSUE THREAD

**Issue by flaneuse** [biothings/discovery-app#4]
Error message: "field analysisCode in $validation is not correctly documented"

Steps to reproduce:
Try to visualize https://raw.githubusercontent.com/SuLab/niaid-data-portal/master/schema/Demo-Extended-Dataset.jsonld on https://discovery.biothings.io/schema-playground

Steps to create .json schema

1. https://discovery.biothings.io/registry
2. Search for a dataset (NIAID); select NIAID dataset
3. Create namespace, class
4. Add custom property `analysisCode` of type `schema:SoftwareSourceCode`

**Comment by marcodarko** [comment]
prop type should be `"@type": "rdf:Property"` not `"@type": "rdfs:Property"` , this issue has been fixed on our editor which caused issues parsing schema.
