### ISSUE TITLE
dataset metadata api endpoint should exclude _meta field by default

### ISSUE THREAD

**Issue by newgene** [biothings/discovery-app#43]
but can be returned with `meta=1/true` query param.

**Comment by newgene** [comment]
will need to coordinate with the downstream applications before deployment.

**Comment by namespacestd0** [comment]
Supported in https://github.com/biothings/discovery-app/blob/671024a6d4cfeaaf8ecb079504ae4d50d089a331/discovery/web/api/dataset.py#L183
