### ISSUE TITLE
Schema viewer shows Controlled Vocabularies as "CreativeWorks"

### ISSUE THREAD

**Issue by flaneuse** [biothings/discovery-app#48]
In [NIAID Dataset](https://discovery.biothings.io/view/niaid/NiaidDataset), the `infectiousAgent` property is shown as a `CreativeWork` with type string and Non-Strict term lookup.  It should just be a (non-strict) enumerated string, not a CreativeWork object.

<img width="1087" alt="Screen Shot 2020-12-11 at 11 40 26 AM" src="https://user-images.githubusercontent.com/8041065/101936085-b5c28980-3ba5-11eb-8689-44fc1f253ea9.png">

**Comment by marcodarko** [comment]
Closing since this is an accurate representation of the current version registered.
