### ISSUE TITLE
Add link to download .jsonld version of schema in Viewer

### ISSUE THREAD

**Issue by flaneuse** [biothings/discovery-app#49]
Would be nice in https://discovery.biothings.io/view/niaid/NiaidDataset (or other schemas) to have a link to download the schema as .jsonld file.

**Comment by marcodarko** [comment]
<img width="1109" alt="Screen Shot 2021-01-26 at 2 47 29 PM" src="https://user-images.githubusercontent.com/23092057/105916203-703b0e00-5fe5-11eb-99bb-dd9bb52425af.png">
A link on the schema's homepage is available > source
