### ISSUE TITLE
Minor: Initial state of /view/{datasetname} is weird

### ISSUE THREAD

**Issue by flaneuse** [biothings/discovery-app#5]
https://discovery.biothings.io/view/niaid/NiaidDataset

Initial state of the toggles isn't synced.  Clicking "show/hide all properties on page" doesn't work unless you uncheck the :star: "show all inherited properties"

**Comment by marcodarko** [comment]
Next update will remove this toggle when the current view doesn't have fields to expand/contract

**Comment by marcodarko** [comment]
Toggle has been hidden on views where it doesn't apply.
