### ISSUE TITLE
Nested properties on Schema viewer don't show required fields

### ISSUE THREAD

**Issue by flaneuse** [biothings/discovery-app#50]
In the [NiaidDataset](), `funding.funder`, `funding.identifier`, and `funding.funder.name` should be [required](https://raw.githubusercontent.com/SuLab/niaid-data-portal/master/schema/NIAIDDataset.json):
```
"monetaryGrant": {
"type": "object",
"@type": "MonetaryGrant",
"description": "Funding that supports (sponsors) the collection of this dataset through some kind of financial contribution",
"properties": {
"funder": {
"description": "An organization associated with a creator or funder of a dataset",
"oneOf": [
{
"$ref": "#/definitions/funder"
},
{
"type": "array",
"items": {
"$ref": "#/definitions/funder"
}
}
]
},
"description": {
"type": "string",
"description": "description about the funding award / grant"
},
"url": {
"type": "string",
"description": "award / grant URL"
},
"identifier": {
"type": "string",
"description": "Unique identifier(s) for the grant(s) used to fund the Dataset"
}
},
"required": [
"funder",
"identifier"
]
}
```

The display doesn't show this:
<img width="1103" alt="Screen Shot 2020-12-11 at 12 29 24 PM" src="https://user-images.githubusercontent.com/8041065/101940830-b579bc80-3bac-11eb-99c1-2b4761337705.png">

**Comment by marcodarko** [comment]
Issue was been addressed with this commit: https://github.com/biothings/discovery-app/commit/6b23652b1d7a8062d0c8d4265c5dead729d9283b 

Children requirements marked in red
