### ISSUE TITLE
Removing a user-created property in DDE editor will drop the wrong property

### ISSUE THREAD

**Issue by gtsueng** [biothings/discovery-app#53]
When clicking on the minus sign for the property `poot`
![image](https://user-images.githubusercontent.com/9200138/102251348-89ff1680-3eb9-11eb-883b-1202fc2a5dcb.png)

The prompt to remove `poot` pops up, indicating it's the property I'm trying to remove:
![image](https://user-images.githubusercontent.com/9200138/102251451-ac912f80-3eb9-11eb-8d8c-503717a614cd.png)

However, the result is that `keepThis` disappears. And the `poot` I don't want is still there
![image](https://user-images.githubusercontent.com/9200138/102251509-bfa3ff80-3eb9-11eb-8894-47b89ac0d5c6.png)

**Comment by marcodarko** [comment]
Previous logic was flawed and removed the last item no matter what, removal is now based on exact match based on "label" field of each property.
