### ISSUE TITLE
"Recently Updated" sorting is not working

### ISSUE THREAD

**Issue by andrewsu** [biothings/discovery-app#54]
On https://discovery.biothings.io/dataset, I selected the "Recently Updated" sorting option but that does not appear to work...

![image](https://user-images.githubusercontent.com/2635409/102255998-b027b500-3ebf-11eb-85bc-8d17529f7bf4.png)

**Comment by marcodarko** [comment]
Issue was resolved when we switched to backend pagination and adding missing dates to old docs with no creation/updated dates.  Changes are live now.
