### ISSUE TITLE
Allow searching by user name

### ISSUE THREAD

**Issue by andrewsu** [biothings/discovery-app#55]
For example, https://discovery.biothings.io/dataset/1bc165a9897269ef was registered by [fluomics](https://discovery.biothings.io/contributor/fluomics).  But searching "fluomics" at https://discovery.biothings.io/dataset returns zero results. I was expecting to see all datasets shown at https://discovery.biothings.io/contributor/fluomics.

![image](https://user-images.githubusercontent.com/2635409/102256459-48be3500-3ec0-11eb-9bc1-60d7ff70068c.png)

**Comment by namespacestd0** [comment]
Implemented in https://github.com/biothings/discovery-app/commit/8491a00599b6eb4009315d953e1a11503e8d6ff9. Just deployed.
