### ISSUE TITLE
Improve display options for ontology lookup

### ISSUE THREAD

**Issue by flaneuse** [biothings/discovery-app#56]
Suggestion from user from NIAID DDWG: when he was adding the species "Mycobacterium tuberculosis", he wanted to add a subspecies ("Mycobacterium tuberculosis H37RV") but couldn't find it in the list, even though it is in the ontology.  Are there ways to make it clearer that there are more specific versions of M. tuberculosis and try to find it?

**Comment by flaneuse** [comment]
Not sure why H37Rv isn't listed; it's in the [ontology](http://www.ontobee.org/ontology/NCBITaxon?iri=http://purl.obolibrary.org/obo/NCBITaxon_83332).

<img width="585" alt="Screen Shot 2020-12-15 at 1 21 38 PM" src="https://user-images.githubusercontent.com/8041065/102262276-7adb9100-3ed8-11eb-9006-377e645fe4bd.png">

In any case, it would be useful to have a search bar at the top to refine the results and filter as you type.

**Comment by marcodarko** [comment]
Improved component available now, allowing for multiple searches, filtering, and item preview.
