### ISSUE TITLE
Add an option within /guide to add in additional custom fields

### ISSUE THREAD

**Issue by flaneuse** [biothings/discovery-app#57]
An extension off of the current /guide capability... a member of the DDWG mentioned that it would be nice to add custom fields to the NIAID dataset guide, to add additional fields.

Obviously, they can go back and add additional data through the .json modifications, but it'd be nice to add an option to the GUI too.  Something like "Add custom field" with a triplicate: name, type, value.  Would be consistent with our view that the NIAID dataset should be a common base with extendable options.

Not a high priority (especially since custom objects gets complicated), but something worth thinking about.

**Comment by NikkiBytes** [comment]
The guide now allows to add user defined properties to user defined classes.
