### ISSUE TITLE
Minor UX: copy text input from measurementTechnique to "add custom value" input box when registering Dataset

### ISSUE THREAD

**Issue by flaneuse** [biothings/discovery-app#6]
When you search for a term against an ontology, it'd be nice to transfer the input search term to the "Didn't find what you are looking for? Enter value here:" input box.

Steps to reproduce:
1. https://discovery.biothings.io/guide/niaid
2. Add "metagenomics" as measurementTechnique
3. Idealized behavior: "metagenomics" would already appear in "Didn't find what you are looking for? Enter value here:" so you can change or submit.

**Comment by marcodarko** [comment]
implemented suggested improvement, user input will now be pre-populated on input element
