### ISSUE TITLE
Add link to /guide/niaid from /niaid

### ISSUE THREAD

**Issue by flaneuse** [biothings/discovery-app#65]
Add a link to https://discovery.biothings.io/guide/niaid

from
https://discovery.biothings.io/niaid/about
https://discovery.biothings.io/niaid/

to register a dataset.

Might also want to link to https://discovery.biothings.io/portal/niaid?

**Comment by marcodarko** [comment]
Link to NIAID guide was added to main page as discussed in a meeting long ago... :P
