### ISSUE TITLE
Allow sorting of properties in a class in alphabetical order

### ISSUE THREAD

**Issue by gtsueng** [biothings/discovery-app#67]
When extending a schema, enable the properties to be sorted in alphabetical order.  This makes it easier when re-creating a schema using the DDE (can quickly go through line-by-line comparison of properties, without having to type them in). Eg- if a custom schema uses 45 of the 89 properties in CreativeWork, alphabetical order can make it easier to quickly scan through and select properties.

**Comment by marcodarko** [comment]
Sorting and filtering of class properties is now available on schema editor.
