### ISSUE TITLE
view schema now option in editor doesn't actually go to schema viewer

### ISSUE THREAD

**Issue by gtsueng** [biothings/discovery-app#68]
After saving a newly drafted schema, you have the option of viewing the schema:
![image](https://user-images.githubusercontent.com/9200138/102543856-c0c75f00-4068-11eb-8366-103c8e1af527.png)

Then it builds up your anticipation for seeing the new schema:
![image](https://user-images.githubusercontent.com/9200138/102543901-d76db600-4068-11eb-9335-da0dd6d756c8.png)

Only to bring you back to the editor
![image](https://user-images.githubusercontent.com/9200138/102543801-adb48f00-4068-11eb-9ca4-519059a1e64d.png)

I guess I was expecting it to take me to the DDE schema playground viewer, but it doesn't actually take you anywhere.

**Comment by marcodarko** [comment]
This feature has been changed, it no longer requires step 1 and 2, it also retries in case the conflict is due to main branch called 'master'.  Closing since it is now outdated but reopen if new issues come up.
