### ISSUE TITLE
Bug: When registering a dataset, children seem to be inheriting their parent's marginality

### ISSUE THREAD

**Issue by flaneuse** [biothings/discovery-app#7]
Bug: When registering a dataset, children seem to be inheriting their parent's marginality

Example: Why is `url` a required property on `creator` in NIAID?  It should be optional according to the schema:
https://github.com/SuLab/niaid-data-portal/blob/master/schema/NIAIDDataset.json

Steps to reproduce:
1. https://discovery.biothings.io/guide/niaid
2. Add a creator; try to bypass url.

See also: funding:description, funding:url, funding:parentOrganization, ...

**Comment by marcodarko** [comment]
The updated guide at https://discovery.biothings.io/guide/niaid lets the users skip non-required fields if they are not specified as required. Skipped fields will be ignored in the final output.
