### ISSUE TITLE
Schema Viewer doesn't allow variables with `_` prefix

### ISSUE THREAD

**Issue by flaneuse** [biothings/discovery-app#71]
Might be a design decision... I had included the Elasticsearch-assigned `_version` in my schema, but it's not allowed.

**Comment by flaneuse** [comment]
See also `@type`.  I've used it in CViSB to define a Dataset type throughout, which breaks the registration.  See [small example](https://github.com/cvisb/cvisb_data/blob/master/sample-viewer-api/src/static/schemas/cvisb_h.jsonld)

`@type` is a commonly used property, so I would advocate that mandating camelCase starting with a lower case letter is overly prescriptive.  https://developers.google.com/search/docs/data-types/dataset

**Comment by marcodarko** [comment]
I have relaxed the validation and allowed everything, However I have also included this link https://schema.org/docs/styleguide.html right under for reference. Preferably we stick to it.
