### ISSUE TITLE
Mild routing bug: back button doesn't go back properly in Chrome

### ISSUE THREAD

**Issue by flaneuse** [biothings/discovery-app#72]
Steps to reproduce:

1. https://discovery.biothings.io/portal/niaid
2. Click on Datasets on right nav bar (routes to https://discovery.biothings.io/dataset?guide=/guide/niaid)
3. Clicking Back button on Chrome routes to https://discovery.biothings.io/dataset instead of https://discovery.biothings.io/portal/niaid

**Comment by marcodarko** [comment]
I don't experience the same on same browser  but I do implement a history push on searches to go back to previous searches that might be interfering with this if you search for something but this shouldn't be the case here.

**Comment by NikkiBytes** [comment]
DDE is now server side rendered application, therefore the issue is not relevant and is resolved.
