### ISSUE TITLE
Schema editor: allow to search for GitHub repos

### ISSUE THREAD

**Issue by flaneuse** [biothings/discovery-app#75]
When saving a schema that I generated using the schema editor, I have the option to save it to GitHub, and I can pull repos that I have write access too.

That's really cool, but I have a lot of repos, and I can't find the one I'm looking for (for some reason it doesn't think I have write access to outbreak?).  It'd be helpful to be able to type search within that list to narrow down my options.

<img width="1477" alt="Screen Shot 2021-01-22 at 8 14 47 PM" src="https://user-images.githubusercontent.com/8041065/105565942-ffe37280-5cee-11eb-9279-ea5723d465f2.png">

**Comment by marcodarko** [comment]
You can now search/filter your repos fetched by name.
