### ISSUE TITLE
Schema editor: Umm, how do I go back?

### ISSUE THREAD

**Issue by flaneuse** [biothings/discovery-app#76]
I went to validate my schema on the "validation" button on the schema editor, and now I can't figure out how to get back to edit it.  :(

<img width="1620" alt="Screen Shot 2021-01-22 at 8 16 38 PM" src="https://user-images.githubusercontent.com/8041065/105565992-3ae5a600-5cef-11eb-969c-57a1b31973cb.png">

**Comment by marcodarko** [comment]
Refined layout, clearer way to toggle validation process.
