### ISSUE TITLE
Schema editor: how do I go back and edit a new property I added?

### ISSUE THREAD

**Issue by flaneuse** [biothings/discovery-app#79]
Say I want to edit the description for `gene` -- can I do that within the form?

<img width="1090" alt="Screen Shot 2021-01-22 at 8 30 23 PM" src="https://user-images.githubusercontent.com/8041065/105566243-ba27a980-5cf0-11eb-8e32-1144b0116b9c.png">

**Comment by marcodarko** [comment]
<img width="894" alt="Screen Shot 2021-01-26 at 2 30 33 PM" src="https://user-images.githubusercontent.com/23092057/105914399-2c470980-5fe3-11eb-99fb-44a8141b9050.png">
You can now do this, update is published.
