### ISSUE TITLE
Enhancement: NCBI taxon ontology not loading

### ISSUE THREAD

**Issue by flaneuse** [biothings/discovery-app#8]
Steps to reproduce:
1. https://discovery.biothings.io/guide/niaid
2. try to lookup species or pathogen, using 9606, human, homo sapiens, etc.: https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=9606

... --> no preview

**Comment by marcodarko** [comment]
owl file on previous version: http://purl.obolibrary.org/obo/ncbitaxon.owl
took too long to download and API returned 0 docs.

Changed to vocabulary to include 2 separate files to improve speed and return results.

Changed to: 

`"vocabulary": {
              "ontology": ["ncbitaxon"],
              "children_of": ["http://purl.obolibrary.org/obo/NCBITaxon_10239", "http://purl.obolibrary.org/obo/NCBITaxon_131567l"]
            },`
