### ISSUE TITLE
Schema editor: visualize/registration doesn't work from GitHub saving

### ISSUE THREAD

**Issue by flaneuse** [biothings/discovery-app#81]
After saving to GitHub, I copied the GH url provided in the box to try to visualize it, but it gave me a 404 error.

File should point to https://github.com/flaneuse/hCoV19-sitrep/blob/master/mutation_schema-mutation.jsonld.

I think it's a `main` vs. `master` branch error.

<img width="787" alt="Screen Shot 2021-01-22 at 8 40 17 PM" src="https://user-images.githubusercontent.com/8041065/105566527-4b4b5000-5cf2-11eb-9713-99850e7d4822.png">

**Comment by marcodarko** [comment]
Implemented a retry with branch "main"  if "master" fails, hopefully github will eventually handle this on their own.
