### ISSUE TITLE
duplicated schema class table in the schema viewer

### ISSUE THREAD

**Issue by newgene** [biothings/discovery-app#83]
e.g. `n3c:Dataset` appears twice in this page:

https://discovery.biothings.io/view/n3c/Dataset (click "validation view" to view the schema classes)

![image](https://user-images.githubusercontent.com/130158/105777574-7961a780-5f1f-11eb-86a1-4def9923289a.png)

**Comment by marcodarko** [comment]
I was previously pulling all parent data by "label" which returns multiple hits when it's the same eg. "Dataset", now it takes the curie into consideration schema:Dataset != n3c:Dataset. Fix has been published.
