### ISSUE TITLE
validate _id/identifier field in the metadata form

### ISSUE THREAD

**Issue by newgene** [biothings/discovery-app#84]
Currently the metadata form does not check if the hashed `_id` field is duplicated or not. When this happens, backend will return a conflict error:

![image](https://user-images.githubusercontent.com/130158/105780672-d82a1f80-5f25-11eb-8bae-cf879d03f1a7.png)

We should add the check on the frontend to prevent this happens. The check can be associated with the `identifier` field.

**Comment by marcodarko** [comment]
Forms now check for duplicates based on this field, Update is published.
