### ISSUE TITLE
Dataset registration: disallow multiple selections of same item

### ISSUE THREAD

**Issue by andrewsu** [biothings/discovery-app#88]
In the screenshot below, I can select "RNA-seq" multiple times by repeatedly clicking the green "+". I expect that to only show up once.  Ideally, there would also be a visual indicator that the item was successfully added on click (perhaps changing that green "+") when I'm not scrolled down far enough to see the "Selections" box...

![image](https://user-images.githubusercontent.com/2635409/108022580-ac0a3780-6fd5-11eb-8193-b6599a18ce18.png)

**Comment by marcodarko** [comment]
<img width="675" alt="Screen Shot 2021-02-16 at 9 22 16 AM" src="https://user-images.githubusercontent.com/23092057/108098963-db9e5b80-7038-11eb-91e2-c2146fc5e420.png">

Will check for matching labels if available and not allow duplicates, thank you!!
