### ISSUE TITLE
Duplicate results in schema registry search

### ISSUE THREAD

**Issue by gtsueng** [biothings/discovery-app#89]
As seen when you search for a Dataset schema, there are 2 outbreak schemas--One which is a derivative of Dataset, and one which is a derivative of CreativeWork (top and bottom entry in picture). This is weird since Dataset itself is a derivative of CreativeWork in schema.org. When you visualize the outbreak Dataset schema, you see it's lineage: ` schema:Thing>schema:CreativeWork>schema:Dataset>outbreak:Dataset ` 

The results do NOT include an outbreak:Dataset that is a derivative of schema:Thing so it seems inconsistent to include a search result listing it as a derivative of CreativeWork.  
![image](https://user-images.githubusercontent.com/9200138/109850303-358d4c80-7c07-11eb-938c-e52ae06af761.png)

**Comment by gtsueng** [comment]
Suspected to be related to: https://github.com/biothings/discovery-app/issues/103 and https://github.com/biothings/discovery-app/issues/77

**Comment by NikkiBytes** [comment]
Issue is resolved.
