### ISSUE TITLE
Schema playground: non-existing namespace show cached schemas

### ISSUE THREAD

**Issue by newgene** [biothings/discovery-app#9]
This issue seems having two behaviors:

1. If accessing https://discovery.biothings.io/view/ctsa_blah/ for the first time, the page shows empty schema list, which is correct, but need a more explicit msg saying the namespace does not exist.

2. If accessing https://discovery.biothings.io/view/ctsa_blah/ after I viewed another schema (e.g. by clicking one of example links), somehow, the first link shows the content from the previous schema. Looks like it picked up the cached data from the local storage.

**Comment by marcodarko** [comment]
Changed logic to save temporary views to local storage by temp namespace, and going back to the same /tempname after navigating away should only work if the /tempname matches an entry on local storage otherwise you will be taken to playground
